(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes
lib.webFontTxtFilters = {}; 

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#000000",
	webfonts: {},
	manifest: [
		{src:"images/freiesMagaziniPadAppSingle.png", id:"freiesMagaziniPadAppSingle"}
	]
};



lib.webfontAvailable = function(family) { 
	lib.properties.webfonts[family] = true;
	var txtFilters = lib.webFontTxtFilters && lib.webFontTxtFilters[family] || [];
	for(var f = 0; f < txtFilters.length; ++f) {
		txtFilters[f].updateCache();
	}
};
// symbols:



(lib.freiesMagaziniPadAppSingle = function() {
	this.initialize(img.freiesMagaziniPadAppSingle);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,340,435);


(lib.Slogan4iPadApp = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgfBAIgEAAIgCAAIgBgBIgBgCIAAh5IAAgBIACgBIABAAIAEAAIADAAIACAAIACABIAAABIAAANIAIgHIAHgGIAIgCIAHgBQAJAAAHADQAHADAEAHQAEAGACAJQACAIAAAKQAAAMgCAHQgDAJgFAGQgFAHgHADQgHAEgJAAIgFgBIgHgDIgHgDIgGgHIAAAsIAAACIgCABIgCAAgAgDgxIgGADIgHAFIgHAIIAAAhQAHAIAGAFQAGAEAEAAQAHAAAEgDQAEgDADgFIAEgIIABgNIgBgNQgBgGgDgFQgCgFgEgDQgEgDgGAAg");
	this.shape.setTransform(138.5,14.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgfBAIgEAAIgDAAIgBgBIAAgCIAAh5IAAgBIABgBIADAAIADAAIADAAIADAAIABABIAAABIAAANIAIgHIAHgGIAIgCIAGgBQAKAAAHADQAHADADAHQAFAGACAJQACAIAAAKQAAAMgCAHQgDAJgFAGQgFAHgHADQgHAEgJAAIgGgBIgGgDIgGgDIgHgHIAAAsIAAACIgBABIgDAAgAgDgxIgGADIgGAFIgIAIIAAAhQAGAIAHAFQAFAEAGAAQAFAAAFgDQAEgDADgFIAEgIIABgNIgBgNQgBgGgCgFQgDgFgEgDQgFgDgFAAg");
	this.shape_1.setTransform(128,14.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAtA/IgEAAIgDAAIgCgBIAAgCIgLgeIgzAAIgKAeIAAABIgCACIgDAAIgEAAIgFAAIgDgBIAAgCIABgDIAqh0IACgBIABgCIADAAIAEAAIAEAAIADAAIACACIABABIArB0IABADIgBACIgCABgAAUAQIgUg9IgVA9IApAAg");
	this.shape_2.setTransform(116.7,10.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgSAGQgBAAAAAAQgBAAAAAAQgBAAAAgBQAAAAgBAAIgBgFIABgEQABAAAAAAQAAgBABAAQAAAAABAAQAAAAABAAIAmAAIABAAIABABIABACIAAACIgBAFQAAAAAAAAQAAABgBAAQAAAAAAAAQgBAAAAAAg");
	this.shape_3.setTransform(107.8,12.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUBAQgGgDgFgHQgEgGgCgJQgCgIAAgKQAAgLADgJQACgIAFgGQAFgHAHgDQAHgDAJAAQAGAAAGADQAHADAGAHIAAgzIAAgCIABgBIADAAIAEAAIAEAAIACAAIACABIAAACIAACAIAAABIgBABIgDABIgDAAIgDAAIgDgBIgBgBIAAgBIAAgMQgHAIgIAEQgHAEgHAAQgKAAgHgEgAgKgKQgEADgDAFQgDADgBAGQgBAGAAAGIABANQABAHACAEQADAFAEADQAEADAHAAIAEgBIAGgCIAHgGIAHgIIAAgjQgHgGgGgEQgGgFgFAAQgGAAgEADg");
	this.shape_4.setTransform(99.2,10.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgRAuQgFgCgEgDQgEgEgDgFQgCgFAAgGQAAgIADgFQADgGAGgCQAGgDAIgBQAIgCAJAAIALAAIAAgHIgBgJQAAgEgDgDIgGgEIgJgBQgEAAgFACIgJADIgGADIgDABIgBAAIgBgBIgBgCIAAgDIAAgEIACgDIAEgDIAHgDIAKgCIAIgBQAJAAAHACQAGACAFAFQAEAEACAGQACAGgBAIIAAA5IAAACIgCABIgFAAIgDAAIgCgBIgBgCIAAgIQgGAGgHADQgHAEgGAAQgHAAgGgCgAgDAEIgJAEQgDACgCADQgBADAAAEQAAAHAEAEQAFAEAIAAQAEAAAFgDQAFgDAGgHIAAgTIgNAAIgJABg");
	this.shape_5.setTransform(89.2,12.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgdA/IgEAAIgDAAIgBgBIAAgCIAAhyQAAgFACgBQAAAAABgBQAAAAABgBQAAAAABAAQABAAAAAAIAbAAIAGABIAJABQAFABAFADQAGADADAEQAEAFACAGQACAGAAAHQAAAKgDAHQgDAIgGADQgGAFgIADQgJADgJABIgPAAIAAAtIAAACIgBABIgDAAgAgVABIAPAAQAGgBAFAAQAFgBAEgEQADgDACgFQACgFAAgGQAAgHgDgFQgDgFgEgDIgJgEIgHAAIgQAAg");
	this.shape_6.setTransform(80.4,10.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAABAIgCAAIgDAAIgBgBIgBgCIAAhWIABgBIABgBIADAAIACAAIAEAAIACAAIABABIAAABIAABWIAAACIgBABIgCAAgAgHguQgCgDAAgFQAAgGACgCQADgCAEAAQAFAAACACQACACAAAGQAAAGgCACQgCABgFAAQgEABgDgCg");
	this.shape_7.setTransform(72.6,10.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgKAvIgJgCIgFgCIgDgDIgCgCIAAgFIAAgDIAAgCIABgBIABgBIADACIAFADIAIACQAEACAGAAIAFgBIAFgDQADgBACgDIABgGQgBgEgBgDIgFgEIgIgEIgGgDIgHgDIgHgEIgGgHQgCgEABgGQgBgFACgFQADgFAEgDQAEgEAFgCQAGgCAHAAIAGABIAHABIAFACIADACIABABIAAACIABABIAAADIAAADIgBACIgBABIAAAAIgDgBIgEgCIgHgCIgHgBIgGABQgDAAgCACIgDAEIgBAFQAAAEACADIAFAEIAFAEIAIADIAIAEIAIADQADADACAEQACAEAAAFQAAAHgDAFQgDAGgEADQgFAEgGACQgGACgGAAg");
	this.shape_8.setTransform(61.9,12.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAABEIgDAAIgCgBIgBgBIgBgBIAAiBIABgBIABgBIACgBIADAAIADAAIADABIABABIABABIAACBIgBABIgBABIgDABg");
	this.shape_9.setTransform(55.7,10.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgRAuQgFgCgEgDQgEgEgDgFQgCgFAAgGQAAgIAEgFQADgGAFgCQAGgDAIgBQAIgCAIAAIAMAAIAAgHIgBgJQAAgEgDgDIgGgEIgJgBQgEAAgFACIgJADIgGADIgDABIgBAAIgBgBIgBgCIAAgDIAAgEIACgDIAEgDIAHgDIAKgCIAIgBQAKAAAGACQAHACAEAFQAEAEACAGQACAGgBAIIAAA5IAAACIgCABIgFAAIgEAAIgBgBIgBgCIAAgIQgGAGgHADQgHAEgGAAQgHAAgGgCgAgDAEIgJAEQgDACgCADQgBADAAAEQAAAHAFAEQADAEAJAAQAEAAAFgDQAGgDAFgHIAAgTIgNAAIgJABg");
	this.shape_10.setTransform(48.4,12.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAMA7QgHAAgFgCQgCgCgEgDQgDgEgBgGIgBgNIAAgxIgNAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgFIAAgDIABgCIABgBIABgBIANAAIAAgVIAAgBIABgBIADAAIAEgBIADABIABAAIABABIABABIAAAVIAWAAIACABIABABIAAACIAAADIAAAFQAAABgBAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgWAAIAAAvQAAAJACAFQADAEAHAAIAEAAIADgBIACgBIACgBIABABIABABIAAABIAAADIAAAFIgBACIgDACIgDABIgEABg");
	this.shape_11.setTransform(35.9,11.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZAuQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIAAgEIABgCIAAgCIABgCIACgDIAlg6IgkAAQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAIgBgFIAAgDIABgDIABgBIABAAIAxAAIABAAIACABIABACIAAADIAAADIAAACIgBADIgBACIgBADIglA7IAnAAIACAAIABABIAAACIABADIgBADIAAACIgBABIgCABg");
	this.shape_12.setTransform(28.8,12.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAMA7QgHAAgFgCQgCgCgEgDQgDgEgBgGIgBgNIAAgxIgNAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgFIAAgDIABgCIABgBIABgBIANAAIAAgVIAAgBIABgBIADAAIAEgBIADABIABAAIABABIABABIAAAVIAWAAIACABIABABIAAACIAAADIAAAFQgBABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgWAAIAAAvQAAAJACAFQADAEAHAAIAEAAIADgBIACgBIACgBIABABIABABIAAABIAAADIAAAFIgBACIgDACIgDABIgEABg");
	this.shape_13.setTransform(21.3,11.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgFgGQgHgGgCgJQgDgJAAgMQAAgKADgJQADgJAGgGQAFgGAIgEQAHgDAIAAQALAAAHADQAHAEAFAFQAEAGADAIQACAHAAAJIAAADQAAACgCABQAAABgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAIg4AAIABANQACAGADAEQAEAEAFACQAGADAFAAIAMgBIAIgDIAGgCIAEgBIABAAIABABIAAACIAAADIAAACIAAACIAAABIgBABIgEACIgGADIgKACIgMABQgJAAgIgDgAgIggQgEACgDAEIgGAJQgBAEAAAGIAtAAQABgNgGgHQgGgHgLAAQgEAAgFACg");
	this.shape_14.setTransform(13.3,12.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgJBAIgFgCIgDgCIgDgBIgBgBIgBgBIAAgCIAAgEIAAgDIABgCIABgCIABAAIACABIADACIAEABIAFABIAFgBQACgBABgCQACgCAAgEIABgKIAAhZIABgBIABgBIACgBIAFAAIADAAIADABIABABIABABIAABaQAAAHgCAHQgBAGgDAFQgDAEgGACQgFADgHAAg");
	this.shape_15.setTransform(4.4,10.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,145.6,24);


(lib.Slogan3freiesMagazin = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E0691A").s().p("AAnBRIgGgBIgEgCIgBgDIAAhSQAAgMgBgFIgFgLQgDgEgEgDQgFgDgGAAQgGABgJAFQgIAHgIALIAABgIgBADIgEACIgGABIgKABIgLgBIgGgBIgDgCIgBgDIAAiSIAAgDIADgCIAGgBIAJgBIAIABIAGABIADACIAAADIAAARQANgOAMgGQALgHAOAAQAPABAKAEQALAFAGAJQAGAJADALQADAMAAAQIAABZIgBADIgDACIgHABIgKABg");
	this.shape.setTransform(190.3,19.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E0691A").s().p("AgJBwIgGgBIgDgCIgBgDIAAiSIABgCIADgDIAGgBIAJgBIAJABIAHABIADADIABACIAACSIgBADIgDACIgHABIgJABgAgShJQgFgEAAgMQABgNAFgFQAEgFANAAQAOAAAEAFQAGAFAAAMQAAANgGAEQgFAFgNAAQgNAAgFgFg");
	this.shape_1.setTransform(177,16.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E0691A").s().p("AgtBPQgFAAgDgDQgCgDAAgHIAAgHIABgFIABgFIABgFIADgFIA2hUIgyAAQgDAAgDgEQgCgEAAgIIABgIIABgFIACgDIAEgBIBYAAIAEAAIADACIACAEIAAAGIAAAIIAAAGIgBAFIgDAEIgDAFIg1BUIA5AAIADAAIACADIABAFIABAIIgBAIIgBAGIgCADIgDAAg");
	this.shape_2.setTransform(166.1,19.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E0691A").s().p("AgiBQQgKgEgHgGQgHgFgEgKQgEgIAAgNQAAgNAFgIQAFgLAKgDQAKgHAPgDQAPgDARAAIAPAAIAAgJIgBgMQgBgFgEgEQgDgDgGgCIgLgCQgLAAgIADIgOAFIgKAFIgHACIgEAAIgCgEIgCgGIAAgHIABgIIADgFIAIgFIAOgFIARgFIARgBQARAAAMADQANAEAIAHQAIAGAEAMQADALAAAPIAABiIgBAEIgGABIgLABIgKgBIgFgBIgCgEIAAgMQgJAKgLAGQgMAFgNAAQgLAAgKgDgAgFAMQgHABgEADQgFAEgCAEQgCAEAAAFQAAAKAFAFQAHAGAKgBQAGABAIgFQAIgEAHgKIAAgZIgQAAg");
	this.shape_3.setTransform(150.5,19.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#E0691A").s().p("AgjBsQgNgDgJgFQgIgFgEgIQgFgHAAgJIACgKIAEgKIAHgJIAJgIQgHgDgEgHQgEgGAAgJQAAgJAEgGQAFgJAHgGQgGgGgDgIQgDgIgBgMQABgNAEgKQAFgKAHgIQAJgGALgEQAMgEANAAIAMABIALACIAvAAQADAAACAEQACADAAAJQAAAIgCAEQgDAEgCgBIgSAAQAEAEACAGIACALQgBAMgEAKQgEAKgIAHQgIAHgLADQgMAEgMAAIgNgCIgLgDIgDAEIgBAFQAAAFADADQAFADAIAAIAiACQAMABAKACQAKADAGAGQAHAGAEAHQAEAIAAAKQgBALgEAKQgFAJgKAIQgKAHgOAEQgOAEgSAAQgTAAgNgDgAgbAyIgDAFIgCAGIgBAEQAAAJAJAEQAIAEAPAAQAHAAAHgBQAHgCADgEQAEgDACgDIACgIQAAgIgHgEQgFgEgLAAIgcgBgAgNhPQgFACgDAEIgFAIIgBAKQAAALAHAHQAGAGAMAAQAEAAAFgCQAEgCADgEIAGgHIABgKQAAgMgHgHQgHgGgJAAQgHAAgEACg");
	this.shape_4.setTransform(135,22.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#E0691A").s().p("AgiBQQgKgEgHgGQgHgFgEgKQgEgIAAgNQAAgNAFgIQAFgLAKgDQAKgHAPgDQAPgDASAAIAOAAIAAgJIgBgMQgBgFgEgEQgDgDgFgCIgMgCQgKAAgJADIgOAFIgLAFIgGACIgEAAIgCgEIgBgGIgBgHIABgIIADgFIAIgFIAOgFIARgFIARgBQARAAANADQAMAEAIAHQAIAGADAMQAEALAAAPIAABiIgBAEIgGABIgKABIgLgBIgFgBIgCgEIAAgMQgJAKgLAGQgMAFgMAAQgMAAgKgDgAgFAMQgHABgFADQgEAEgCAEQgDAEAAAFQABAKAFAFQAHAGAKgBQAHABAHgFQAIgEAHgKIAAgZIgQAAg");
	this.shape_5.setTransform(118.2,19.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#E0691A").s().p("ABeBrIgHgCIgDgCIgBgCIAAiuIAAAAIg+CuIgDADIgEACIgGACIgIAAIgJgBIgHgBIgEgDIgCgCIg8iuIgBAAIAACuIAAACIgEACIgGACIgKABIgKgBIgHgCIgDgCIgBgCIAAi+QAAgJAFgEQAEgFAIABIAcAAIANABQAGABAEADQAEADACAFIAFALIAtB/IAAAAIAwh/IAFgLIAGgIQADgDAFgBIALgBIAdAAIAIABIAFADIAEAGIABAHIAAC+IgBACIgEACIgGACIgKABg");
	this.shape_6.setTransform(95.4,16.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgWBRIgOgDIgKgDIgFgEIgDgFIgBgMIAAgIIABgEIACgCIADgBIAFACIAJAEIANAGQAGABAKAAIAIAAIAHgEIAFgFIABgIQAAgFgCgEIgJgGIgJgFIgNgFIgNgGQgHgEgFgDQgFgGgDgIQgDgHAAgKQAAgLAEgJQAFgJAHgGQAIgGALgEQAMgDALAAIAOABIAMACIAJAEIAFACIACADIABADIABAEIAAAHIAAAHIgBAEIgCADIgCAAIgFgCIgIgDIgKgEIgPgCIgIABIgHAEIgDAFIgBAGQAAAGACADIAJAGIAJAFIAOAFIANAGQAGAEAGADQAFAGADAHQADAIAAAKQAAAMgFAKQgEAJgJAHQgJAGgLADQgMAEgMAAg");
	this.shape_7.setTransform(73.9,19.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgaBOQgPgFgLgLQgKgKgEgPQgFgQAAgUQAAgSAFgQQAFgQAKgLQAJgKAPgGQAOgGAPAAQATAAANAGQANAFAJAJQAIAKAEAOQAEANAAAPIAAAHQAAAGgDAEQgDADgGAAIhYAAQAAAKACAHQACAIAFAGQAEAEAIAEQAHACAKABIATgCIAPgEIAKgDIAGgCIADABIABACIABAEIAAAHIAAAGIgBAFIgBADIgBACIgGADIgMAEIgRADIgVACQgSAAgOgFgAgKgxQgHADgDAEQgEAGgCAHIgCAOIA7AAQABgRgHgLQgIgJgQgBQgFAAgGAEg");
	this.shape_8.setTransform(58.4,19.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgJBwIgGgBIgEgCIgBgDIAAiSIABgCIAEgDIAGgBIAJgBIAJABIAHABIAEADIABACIAACSIgBADIgEACIgHABIgJABgAgShJQgFgEABgMQAAgNAEgFQAGgFAMAAQANAAAFAFQAGAFgBAMQABANgGAEQgFAFgNAAQgNAAgFgFg");
	this.shape_9.setTransform(45.8,16.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgbBOQgOgFgLgLQgKgKgEgPQgFgQAAgUQAAgSAFgQQAFgQAKgLQAJgKAPgGQANgGAQAAQATAAANAGQANAFAJAJQAIAKAEAOQAEANAAAPIAAAHQAAAGgDAEQgEADgFAAIhYAAQAAAKABAHQADAIAFAGQAFAEAHAEQAHACAKABIATgCIAOgEIAKgDIAHgCIACABIACACIABAEIAAAHIAAAGIgBAFIgBADIgBACIgGADIgNAEIgRADIgUACQgSAAgPgFgAgKgxQgHADgDAEQgEAGgCAHIgCAOIA8AAQAAgRgHgLQgIgJgQgBQgFAAgGAEg");
	this.shape_10.setTransform(33,19.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgjBRIgGgBIgEgCIgBgDIAAiSIABgDIADgCIAGgBIAIgBIAIABIAGABIADACIAAADIAAASIALgOIAJgIIAJgEIAJgCIAEAAIAGACIAEABIAEACIABABIAAADIABAFIAAAKIgBAJIAAAHIgCACIgDABIgDgBIgDAAIgFgCIgFAAIgHABIgIAEIgIAIIgGANIAABaIgBADIgDACIgHABIgKABg");
	this.shape_11.setTransform(19.6,19.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgPB0IgHgBIgDgCIgCgDIAAh2IgSAAQgDAAgBgEQgCgEAAgJIAAgIIACgFIABgDIADgBIASAAIAAgNQABgPADgLQADgLAGgIQAHgIAIgDQAJgEANAAIANABIAJACIAEADIACADIABAFIAAAIIAAAIIgBAEIgBADIgCAAIgCAAIgEgCIgFgBIgGgBIgIACIgFAEIgEAIIgBAMIAAAOIAbAAIADABIACADIACAFIAAAIQAAAJgCAEQgCAEgDAAIgbAAIAAB2IgBADIgDACIgGABIgIAAg");
	this.shape_12.setTransform(7.7,15.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,201.5,38);


(lib.Slogan2Kostenlos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape.setTransform(254.7,12.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgFgGQgGgGgDgJQgDgJAAgMQAAgKADgJQADgJAGgGQAFgGAIgEQAIgDAHAAQAKAAAIADQAHAEAFAFQAEAGADAIQACAHAAAJIAAADQAAACgCABQAAABgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAIg4AAIABANQABAGAEAEQADAEAGACQAFADAHAAIALgBIAIgDIAGgCIAEgBIABAAIAAABIABACIAAADIAAACIAAACIgBABIgBABIgCACIgHADIgKACIgMABQgJAAgIgDgAgIggQgFACgDAEIgEAJQgCAEAAAGIAuAAQAAgNgGgHQgGgHgMAAQgDAAgFACg");
	this.shape_1.setTransform(244.5,12.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_2.setTransform(234.3,12.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAMA7QgHAAgFgCQgCgCgEgDQgDgEgBgGIgBgNIAAgxIgNAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgFIAAgDIABgCIABgBIABgBIANAAIAAgVIAAgBIABgBIADAAIAEgBIADABIABAAIABABIABABIAAAVIAWAAIACABIABABIAAACIAAADIAAAFQgBABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgWAAIAAAvQAAAJACAFQADAEAHAAIAEAAIADgBIACgBIACgBIABABIABABIAAABIAAADIAAAFIgBACIgDACIgDABIgEABg");
	this.shape_3.setTransform(221,11.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgQAuQgGgCgEgDQgEgEgCgFQgCgFAAgGQAAgIACgFQADgGAGgCQAGgDAIgBQAJgCAIAAIAMAAIAAgHIgBgJQgBgEgDgDIgGgEIgJgBQgFAAgEACIgIADIgGADIgEABIgCAAIgBgBIAAgCIAAgDIAAgEIACgDIAFgDIAHgDIAJgCIAIgBQAKAAAGACQAHACAEAFQAEAEACAGQACAGAAAIIAAA5IgBACIgDABIgDAAIgFAAIgCgBIAAgCIAAgIQgGAGgHADQgHAEgGAAQgHAAgFgCgAgEAEIgIAEQgDACgBADQgCADAAAEQAAAHAEAEQAFAEAHAAQAFAAAGgDQAEgDAHgHIAAgTIgOAAIgKABg");
	this.shape_4.setTransform(213,12.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_5.setTransform(203.3,12.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgSAsQgIgDgGgGQgFgGgDgJQgCgJAAgLQAAgJACgJQADgJAGgGQAFgHAJgDQAIgEAJAAQALAAAIADQAIADAGAHQAFAGADAJQACAIAAALQAAAJgCAJQgDAJgGAHQgFAGgJAEQgIAEgKAAQgKAAgIgEgAgLgfQgFADgDAEQgEAFgBAGQgCAHAAAGQAAAGACAHQABAGADAFQADAEAFADQAGADAGAAQAGAAAGgDQAFgCADgFQAEgEABgHQACgGAAgHQAAgGgCgGQgBgGgDgFQgDgFgFgDQgGgCgHAAQgFAAgGACg");
	this.shape_6.setTransform(192.8,12.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AA8A/IgEAAIgDAAIgBgBIAAgCIAAhsIgBAAIgsBtIgBABIgCABIgCAAIgCAAIgDAAIgDAAIgBgBIAAgBIgshtIAABsIAAACIgBABIgDAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhyQAAgEACgCQACgCADAAIAKAAIAGABIAEABIADAEIACAFIAjBZIAAAAIAlhZIACgGIAEgDIACgBIAFgBIALAAIADABIACABIABACIABAEIAAByIAAACIgCABIgCAAg");
	this.shape_7.setTransform(179,10.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_8.setTransform(160.7,12.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgGgGgCgJQgDgJAAgMQAAgKADgJQADgJAFgGQAGgGAIgEQAHgDAJAAQAKAAAHADQAHAEAFAFQAEAGADAIQACAHAAAJIAAADQAAACgCABQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIg3AAIABANQACAGADAEQADAEAGACQAGADAFAAIALgBIAJgDIAGgCIADgBIACAAIABABIAAACIAAADIAAACIAAACIAAABIgBABIgEACIgHADIgJACIgMABQgJAAgIgDgAgIggQgEACgDAEIgGAJQgBAEAAAGIAtAAQABgNgGgHQgGgHgLAAQgFAAgEACg");
	this.shape_9.setTransform(150.5,12.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUBAQgGgDgFgHQgEgGgCgJQgCgIAAgKQAAgLADgJQACgIAFgGQAFgHAHgDQAHgDAJAAQAGAAAGADQAHADAGAHIAAgzIAAgCIABgBIADAAIAEAAIAEAAIACAAIACABIAAACIAACAIAAABIgBABIgDABIgDAAIgDAAIgDgBIgBgBIAAgBIAAgMQgHAIgIAEQgHAEgHAAQgKAAgHgEgAgKgKQgEADgDAFQgDADgBAGQgBAGAAAGIABANQABAHACAEQADAFAEADQAEADAHAAIAEgBIAGgCIAHgGIAHgIIAAgjQgHgGgGgEQgGgFgFAAQgGAAgEADg");
	this.shape_10.setTransform(140,10.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgFgGgDgJQgDgJAAgMQAAgKADgJQADgJAFgGQAGgGAIgEQAIgDAIAAQAJAAAIADQAHAEAFAFQAFAGACAIQACAHAAAJIAAADQAAACgCABQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIg3AAIABANQACAGADAEQAEAEAFACQAFADAHAAIAKgBIAJgDIAGgCIADgBIACAAIAAABIABACIAAADIAAACIAAACIgBABIgBABIgDACIgHADIgJACIgMABQgJAAgIgDgAgIggQgEACgDAEIgFAJQgCAEAAAGIAtAAQABgNgGgHQgGgHgLAAQgFAAgEACg");
	this.shape_11.setTransform(130,12.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgMBSIgDgBIgCgBIgBgCIAAgCIAAgCIAAgCIABgDIABgBIABAAIABAAIAFAAIAFgBIAEgCIAAgHIAAgKIAAhaIABgBIABgBIADAAIAEgBIADABIAEAAIABABIAAABIAABaQAAAJgBAHQgCAGgDAEQgEAEgEACQgDACgHAAgAABhAQgBgCAAgFQAAgGABgCQACgCAGAAQAGAAACACQACACAAAGQAAAFgCACQgDACgFAAQgGAAgCgCg");
	this.shape_12.setTransform(121.9,12.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgUBAQgGgDgFgHQgEgGgCgJQgCgIAAgKQAAgLADgJQACgIAFgGQAFgHAHgDQAHgDAJAAQAGAAAGADQAHADAGAHIAAgzIAAgCIABgBIADAAIAEAAIAEAAIACAAIACABIAAACIAACAIAAABIgBABIgDABIgDAAIgDAAIgDgBIgBgBIAAgBIAAgMQgHAIgIAEQgHAEgHAAQgKAAgHgEgAgKgKQgEADgDAFQgDADgBAGQgBAGAAAGIABANQABAHACAEQADAFAEADQAEADAHAAIAEgBIAGgCIAHgGIAHgIIAAgjQgHgGgGgEQgGgFgFAAQgGAAgEADg");
	this.shape_13.setTransform(110.3,10.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_14.setTransform(100.1,12.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape_15.setTransform(89.5,12.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgLAvIgIgCIgFgCIgEgDIgBgCIAAgFIAAgDIAAgCIABgBIABgBIAEACIAEADIAIACQAEACAFAAIAGgBIAFgDQADgBACgDIABgGQgBgEgBgDIgFgEIgIgEIgFgDIgIgDIgHgEIgGgHQgCgEAAgGQAAgFACgFQACgFAEgDQAFgEAFgCQAHgCAGAAIAGABIAHABIAFACIADACIABABIAAACIABABIAAADIAAADIgBACIgBABIgBAAIgCgBIgEgCIgGgCIgIgBIgGABQgDAAgCACIgDAEIgBAFQAAAEACADIAFAEIAFAEIAIADIAIAEIAHADQAEADACAEQABAEABAFQgBAHgCAFQgCAGgFADQgFAEgGACQgGACgGAAg");
	this.shape_16.setTransform(75.9,12.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgSAsQgIgDgGgGQgFgGgDgJQgCgJAAgLQAAgJACgJQADgJAGgGQAFgHAJgDQAIgEAJAAQALAAAIADQAIADAGAHQAFAGADAJQACAIAAALQAAAJgCAJQgDAJgGAHQgFAGgJAEQgIAEgKAAQgKAAgIgEgAgLgfQgFADgDAEQgEAFgBAGQgCAHAAAGQAAAGACAHQABAGADAFQADAEAFADQAGADAGAAQAGAAAGgDQAFgCADgFQAEgEABgHQACgGAAgHQAAgGgCgGQgBgGgDgFQgDgFgFgDQgGgCgHAAQgFAAgGACg");
	this.shape_17.setTransform(66.8,12.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAABEIgCAAIgDgBIgBgBIgBgBIAAiBIABgBIABgBIADgBIACAAIAEAAIACABIABABIAAABIAACBIAAABIgBABIgCABg");
	this.shape_18.setTransform(59.3,10.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_19.setTransform(51.7,12.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgFgGgDgJQgDgJAAgMQAAgKADgJQADgJAFgGQAGgGAIgEQAIgDAIAAQAKAAAHADQAHAEAFAFQAEAGADAIQACAHAAAJIAAADQAAACgCABQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIg3AAIABANQACAGADAEQAEAEAFACQAGADAFAAIALgBIAJgDIAGgCIADgBIACAAIABABIAAACIAAADIAAACIAAACIAAABIgCABIgDACIgHADIgJACIgMABQgJAAgIgDgAgIggQgEACgDAEIgGAJQgBAEAAAGIAtAAQABgNgGgHQgGgHgLAAQgFAAgEACg");
	this.shape_20.setTransform(41.5,12.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAMA7QgHAAgFgCQgCgCgEgDQgDgEgBgGIgBgNIAAgxIgNAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgFIAAgDIABgCIABgBIABgBIANAAIAAgVIAAgBIABgBIADAAIAEgBIADABIABAAIABABIABABIAAAVIAWAAIACABIABABIAAACIAAADIAAAFQAAABgBAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgWAAIAAAvQAAAJACAFQADAEAHAAIAEAAIADgBIACgBIACgBIABABIABABIAAABIAAADIAAAFIgBACIgDACIgDABIgEABg");
	this.shape_21.setTransform(33.2,11.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgLAvIgIgCIgFgCIgEgDIgBgCIAAgFIAAgDIAAgCIABgBIABgBIAEACIAEADIAIACQAEACAGAAIAFgBIAFgDQADgBACgDIAAgGQAAgEgBgDIgFgEIgIgEIgFgDIgIgDIgHgEIgGgHQgCgEAAgGQAAgFACgFQACgFAEgDQAFgEAFgCQAHgCAGAAIAGABIAHABIAFACIADACIABABIAAACIABABIAAADIAAADIgBACIgBABIgBAAIgCgBIgEgCIgGgCIgIgBIgGABQgDAAgCACIgDAEIgBAFQAAAEACADIAFAEIAFAEIAIADIAIAEIAHADQAEADACAEQABAEABAFQgBAHgCAFQgCAGgFADQgFAEgGACQgGACgGAAg");
	this.shape_22.setTransform(26.4,12.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgSAsQgIgDgGgGQgFgGgDgJQgCgJAAgLQAAgJACgJQADgJAGgGQAFgHAJgDQAIgEAJAAQALAAAIADQAIADAGAHQAFAGADAJQACAIAAALQAAAJgCAJQgDAJgGAHQgFAGgJAEQgIAEgKAAQgKAAgIgEgAgLgfQgFADgDAEQgEAFgBAGQgCAHAAAGQAAAGACAHQABAGADAFQADAEAFADQAGADAGAAQAGAAAGgDQAFgCADgFQAEgEABgHQACgGAAgHQAAgGgCgGQgBgGgDgFQgDgFgFgDQgGgCgHAAQgFAAgGACg");
	this.shape_23.setTransform(17.3,12.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAgA/IgFAAIgEgBIgCgCIgsg9IAAA9IAAACIgBABIgDAAIgFAAIgDAAIgDAAIgCgBIAAgCIAAh3IAAgBIACgBIADgBIADAAIAFAAIADABIABABIAAABIAAA4IArg4IABgCIACAAIADgBIAEAAIAEAAIADABIABABIAAABIAAACIgDAEIgoAyIArA6IACAEIAAABIAAABIgBABIgCABg");
	this.shape_24.setTransform(7.8,10.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,262.2,24);


(lib.Slogan1News = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgFgGQgGgGgDgJQgDgJAAgMQAAgKADgJQADgJAGgGQAFgGAIgEQAIgDAHAAQAKAAAIADQAHAEAFAFQAEAGADAIQACAHAAAJIAAADQAAACgCABQAAABgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAIg4AAIABANQABAGAEAEQADAEAGACQAFADAHAAIALgBIAIgDIAGgCIAEgBIABAAIAAABIABACIAAADIAAACIAAACIgBABIgBABIgCACIgHADIgKACIgMABQgJAAgIgDgAgIggQgFACgDAEIgEAJQgCAEAAAGIAuAAQAAgNgGgHQgGgHgMAAQgDAAgFACg");
	this.shape.setTransform(483.4,12.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgLAsQgHgDgFgGQgFgGgDgIQgCgJAAgMQAAgLADgJQADgJAFgGQAGgGAHgDQAIgDAHAAIAIABIAHACIAGADIAEADIABACIABABIAAACIAAADIAAAGQAAAAgBAAQAAABAAAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBIgGgDIgHgEQgDgBgHAAQgJAAgGAJQgHAJABAPQAAAIABAHQACAGADAEQADAEAEADQADACAGAAQAGAAAEgCIAHgEIAGgEIACgBIABAAIABABIABADIAAADIAAADIgBACIAAABIgCACIgDADIgHADIgIADIgJABQgIAAgHgEg");
	this.shape_1.setTransform(474.4,12.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQAvIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAANIAHgJIAEgFIAGgDIAFAAIADAAIAEAAIADACIACABIAAABIABABIAAABIAAAEIAAAEIAAACIgBABIgBAAIgCAAIgDgBIgDgBIgEAAIgFABIgEADIgEAGIgGAJIAAA4IgBACIgBABIgCAAg");
	this.shape_2.setTransform(467.4,12.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape_3.setTransform(458.1,12.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgSAsQgIgDgGgGQgFgGgDgJQgCgJAAgLQAAgJACgJQADgJAGgGQAFgHAJgDQAIgEAJAAQALAAAIADQAIADAGAHQAFAGADAJQACAIAAALQAAAJgCAJQgDAJgGAHQgFAGgJAEQgIAEgKAAQgKAAgIgEgAgLgfQgFADgDAEQgEAFgBAGQgCAHAAAGQAAAGACAHQABAGADAFQADAEAFADQAGADAGAAQAGAAAGgDQAFgCADgFQAEgEABgHQACgGAAgHQAAgGgCgGQgBgGgDgFQgDgFgFgDQgGgCgHAAQgFAAgGACg");
	this.shape_4.setTransform(447.6,12.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOBAIgKgDIgHgEIgEgDIgCgCIAAgFIAAgDIAAgDIABgCIACAAIAEACIAGAEIAKADQAFACAHAAQAEAAAEgCIAIgDIAFgHQACgEAAgFQAAgGgDgEIgGgGIgJgFIgJgFIgKgDQgFgEgEgEQgEgEgDgFQgCgGAAgIQAAgHADgGQADgHAFgEQAFgEAHgCQAHgCAGAAIAJAAIAIACIAGACIAEADIABACIABABIAAACIAAADIAAADIAAACIgBACIgBAAIgEgBIgFgDIgIgEQgFgBgFAAQgEAAgEABIgGAFQgDACgBADQgBADAAAEQAAAFACAEIAHAHIAIAFIAKAFIAKAGIAJAEQAEAFADAFQACAFAAAIQAAAJgDAHQgDAHgGAEQgGAFgIADQgHADgIgBg");
	this.shape_5.setTransform(437.8,10.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_6.setTransform(423.5,12.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgFgGQgGgGgDgJQgDgJAAgMQAAgKADgJQADgJAGgGQAFgGAIgEQAIgDAHAAQAKAAAIADQAHAEAFAFQAEAGADAIQACAHAAAJIAAADQAAACgCABQAAABgBAAQgBAAAAAAQgBABAAAAQgBAAAAAAIg4AAIABANQABAGAEAEQADAEAGACQAFADAHAAIALgBIAIgDIAGgCIAEgBIABAAIAAABIABACIAAADIAAACIAAACIgBABIgBABIgCACIgHADIgKACIgMABQgJAAgIgDgAgIggQgFACgDAEIgEAJQgCAEAAAGIAuAAQAAgNgGgHQgGgHgMAAQgDAAgFACg");
	this.shape_7.setTransform(413.2,12.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfBAIgEAAIgCAAIgBgBIgBgCIAAh5IAAgBIACgBIACAAIADAAIAEAAIABAAIACABIAAABIAAANIAIgHIAIgGIAHgCIAHgBQAJAAAGADQAHADAFAHQAEAGACAJQACAIAAAKQAAAMgDAHQgCAJgFAGQgFAHgHADQgHAEgKAAIgEgBIgHgDIgHgDIgGgHIAAAsIgBACIgBABIgCAAgAgDgxIgGADIgHAFIgHAIIAAAhQAGAIAHAFQAGAEAEAAQAHAAAEgDQAEgDADgFIAEgIIABgNIgBgNQgBgGgDgFQgCgFgEgDQgEgDgHAAg");
	this.shape_8.setTransform(403.3,14.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgYA8QgKgEgIgIQgGgJgEgLQgDgMAAgQQAAgNAEgMQAEgMAGgJQAIgJAKgEQAMgFAMABQAOAAALADQAJAEAIAJQAGAIAEAMQADAMAAAPQAAANgEANQgDAMgHAIQgHAJgLAFQgLAEgNAAQgOAAgKgEgAgRgtQgHAEgEAHQgFAGgCAKQgCAJAAAJQAAAKACAJQACAJAEAIQAFAGAHAEQAHAEAKAAQAKAAAIgEQAHgFAFgGQAEgHACgKQACgJAAgJQAAgJgCgKQgCgJgEgHQgEgGgIgEQgHgFgLAAQgJAAgIAFg");
	this.shape_9.setTransform(391.2,10.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgUBAQgGgDgFgHQgEgGgCgJQgCgIAAgKQAAgLADgJQACgIAFgGQAFgHAHgDQAHgDAJAAQAGAAAGADQAHADAGAHIAAgzIAAgCIABgBIADAAIAEAAIAEAAIACAAIACABIAAACIAACAIAAABIgBABIgDABIgDAAIgDAAIgDgBIgBgBIAAgBIAAgMQgHAIgIAEQgHAEgHAAQgKAAgHgEgAgKgKQgEADgDAFQgDADgBAGQgBAGAAAGIABANQABAHACAEQADAFAEADQAEADAHAAIAEgBIAGgCIAHgGIAHgIIAAgjQgHgGgGgEQgGgFgFAAQgGAAgEADg");
	this.shape_10.setTransform(374.5,10.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_11.setTransform(364.3,12.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape_12.setTransform(353.8,12.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAeAuIgFAAIgCAAIgCgBIgBgBIgUgjIgUAjIgBABIgCABIgCAAIgFAAIgEAAIgDgBIgBgBIABgCIAcgqIgagoIgBgDIABgCIADAAIAFAAIAEAAIADAAIABABIABABIASAhIAVghIAAgBIACgBIACAAIAEAAIAFAAIADAAIAAACIgBADIgZAoIAbAqIABACIgBABIgDABg");
	this.shape_13.setTransform(339.7,12.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape_14.setTransform(330.1,12.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_15.setTransform(319.7,12.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAABAIgCAAIgDAAIgBgBIgBgCIAAhWIABgBIABgBIADAAIACAAIAEAAIACAAIABABIAAABIAABWIAAACIgBABIgCAAgAgHguQgCgDAAgFQAAgGACgCQADgCAEAAQAFAAACACQACACAAAGQAAAGgCACQgCABgFAAQgEABgDgCg");
	this.shape_16.setTransform(312.2,10.6);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgZA/IgEgCQgCgBAAgEIAAhzIAAgBIABgBIADgBIAEAAIAEAAIADABIABABIAAABIAABsIAsAAIABAAIABABIABACIAAAEIAAADIgBACIgBABIgBABg");
	this.shape_17.setTransform(306.4,10.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape_18.setTransform(291.7,12.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgZAuQAAAAgBAAQAAAAgBAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQAAgBAAgBIAAgEIABgCIAAgCIABgCIACgDIAlg6IgkAAQAAAAAAgBQgBAAAAAAQAAAAgBAAQAAgBAAAAIgBgFIAAgDIABgDIABgBIABAAIAxAAIABAAIACABIABACIAAADIAAADIAAACIgBADIgBACIgBADIglA7IAnAAIACAAIABABIAAACIABADIgBADIAAACIgBABIgCABg");
	this.shape_19.setTransform(282.6,12.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgLAvIgHgCIgGgCIgDgDIgCgCIgBgFIAAgDIABgCIABgBIABgBIADACIAGADIAHACQAEACAFAAIAGgBIAGgDQACgBABgDIABgGQAAgEgBgDIgFgEIgHgEIgHgDIgIgDIgHgEIgEgHQgCgEAAgGQAAgFACgFQABgFAEgDQAFgEAGgCQAGgCAFAAIAIABIAGABIAFACIADACIABABIABACIAAABIAAADIAAADIAAACIgBABIgCAAIgCgBIgEgCIgGgCIgJgBIgFABQgDAAgCACIgDAEIgBAFQAAAEACADIAFAEIAFAEIAJADIAIAEIAGADQAEADACAEQACAEgBAFQABAHgDAFQgDAGgEADQgFAEgGACQgGACgGAAg");
	this.shape_20.setTransform(270.3,12.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAABEIgDAAIgCgBIgBgBIAAgBIAAiBIAAgBIABgBIACgBIADAAIAEAAIACABIABABIAAABIAACBIAAABIgBABIgCABg");
	this.shape_21.setTransform(264.1,10.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgQAuQgGgCgEgDQgEgEgCgFQgCgFAAgGQAAgIACgFQADgGAGgCQAGgDAIgBQAJgCAIAAIAMAAIAAgHIgBgJQgCgEgCgDIgGgEIgJgBQgFAAgEACIgIADIgHADIgDABIgCAAIgBgBIAAgCIAAgDIAAgEIACgDIAEgDIAIgDIAJgCIAIgBQAKAAAGACQAHACAEAFQAEAEACAGQABAGABAIIAAA5IgBACIgDABIgEAAIgDAAIgDgBIAAgCIAAgIQgGAGgHADQgHAEgGAAQgHAAgFgCgAgEAEIgIAEQgDACgBADQgCADAAAEQAAAHAEAEQAEAEAIAAQAFAAAGgDQAFgDAGgHIAAgTIgOAAIgKABg");
	this.shape_22.setTransform(256.8,12.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAABAIgDAAIgCAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIADAAIADAAIADAAIABABIABABIAABWIgBACIgBABIgDAAgAgGguQgCgDAAgFQAAgGACgCQACgCAEAAQAFAAADACQACACAAAGQAAAGgCACQgDABgFAAQgFABgBgCg");
	this.shape_23.setTransform(250,10.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQAvIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAANIAHgJIAEgFIAGgDIAFAAIADAAIAEAAIADACIACABIAAABIABABIAAABIAAAEIAAAEIAAACIgBABIgBAAIgCAAIgDgBIgDgBIgEAAIgFABIgEADIgEAGIgGAJIAAA4IgBACIgBABIgCAAg");
	this.shape_24.setTransform(244.8,12.3);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgSAsQgIgDgGgGQgFgGgDgJQgCgJAAgLQAAgJACgJQADgJAGgGQAFgHAJgDQAIgEAJAAQALAAAIADQAIADAGAHQAFAGADAJQACAIAAALQAAAJgCAJQgDAJgGAHQgFAGgJAEQgIAEgKAAQgKAAgIgEgAgLgfQgFADgDAEQgEAFgBAGQgCAHAAAGQAAAGACAHQABAGADAFQADAEAFADQAGADAGAAQAGAAAGgDQAFgCADgFQAEgEABgHQACgGAAgHQAAgGgCgGQgBgGgDgFQgDgFgFgDQgGgCgHAAQgFAAgGACg");
	this.shape_25.setTransform(235.5,12.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAMA7QgHAAgFgCQgCgCgEgDQgDgEgBgGIgBgNIAAgxIgNAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgFIAAgDIABgCIABgBIABgBIANAAIAAgVIAAgBIABgBIADAAIAEgBIADABIABAAIABABIABABIAAAVIAWAAIACABIABABIAAACIAAADIAAAFQAAABgBAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgWAAIAAAvQAAAJACAFQADAEAHAAIAEAAIADgBIACgBIACgBIABABIABABIAAABIAAADIAAAFIgBACIgDACIgDABIgEABg");
	this.shape_26.setTransform(226.9,11.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape_27.setTransform(218.5,12.4);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAAA/IgDAAIgCAAIgCgBIAAgCIAAhsIgjAAIgCAAIgBgBIAAgCIgBgDIABgEIAAgCIABgBIACgBIBVAAIACABIABABIABACIAAAEIAAADIgBACIgBABIgCAAIgjAAIAABsIgBACIgBABIgCAAg");
	this.shape_28.setTransform(209.6,10.7);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgUBAQgGgDgFgHQgEgGgCgJQgCgIAAgKQAAgLADgJQACgIAFgGQAFgHAHgDQAHgDAJAAQAGAAAGADQAHADAGAHIAAgzIAAgCIABgBIADAAIAEAAIAEAAIACAAIACABIAAACIAACAIAAABIgBABIgDABIgDAAIgDAAIgDgBIgBgBIAAgBIAAgMQgHAIgIAEQgHAEgHAAQgKAAgHgEgAgKgKQgEADgDAFQgDADgBAGQgBAGAAAGIABANQABAHACAEQADAFAEADQAEADAHAAIAEgBIAGgCIAHgGIAHgIIAAgjQgHgGgGgEQgGgFgFAAQgGAAgEADg");
	this.shape_29.setTransform(194.7,10.3);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_30.setTransform(184.5,12.3);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgUAsQgGgDgDgFQgEgFgCgGQgBgHAAgKIAAgzIAAgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAAxQAAAIABAEQABAFADADQACAEADABQAEACAEAAQAFAAAGgEQAGgEAGgJIAAg7IABgBIABgBIACgBIAEAAIAEAAIADABIABABIAAABIAABWIAAABIgBABIgCABIgEAAIgDAAIgDgBIgBgBIAAgBIAAgMQgIAIgHAEQgHAEgGAAQgJAAgGgDg");
	this.shape_31.setTransform(174,12.4);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgFgGgDgJQgDgJAAgMQAAgKADgJQADgJAFgGQAGgGAIgEQAIgDAIAAQAJAAAIADQAHAEAFAFQAFAGACAIQACAHAAAJIAAADQAAACgCABQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIg3AAIABANQACAGADAEQAEAEAFACQAFADAHAAIAKgBIAJgDIAGgCIADgBIACAAIAAABIABACIAAADIAAACIAAACIgBABIgBABIgDACIgHADIgJACIgMABQgJAAgIgDgAgIggQgEACgDAEIgFAJQgCAEAAAGIAtAAQABgNgGgHQgGgHgLAAQgFAAgEACg");
	this.shape_32.setTransform(159.3,12.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgUBAQgGgDgFgHQgEgGgCgJQgCgIAAgKQAAgLADgJQACgIAFgGQAFgHAHgDQAHgDAJAAQAGAAAGADQAHADAGAHIAAgzIAAgCIABgBIADAAIAEAAIAEAAIACAAIACABIAAACIAACAIAAABIgBABIgDABIgDAAIgDAAIgDgBIgBgBIAAgBIAAgMQgHAIgIAEQgHAEgHAAQgKAAgHgEgAgKgKQgEADgDAFQgDADgBAGQgBAGAAAGIABANQABAHACAEQADAFAEADQAEADAHAAIAEgBIAGgCIAHgGIAHgIIAAgjQgHgGgGgEQgGgFgFAAQgGAAgEADg");
	this.shape_33.setTransform(148.8,10.3);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_34.setTransform(138.6,12.3);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgUA+QgGgDgDgFQgEgFgCgHQgBgHAAgJIAAg0IAAgBIABgBIADAAIAEgBIAEABIACAAIACABIAAABIAAAyQAAAHABAFQABAFADADQACADADABQAEACAEABQAFAAAGgFQAGgEAGgIIAAg8IABgBIABgBIACAAIAEgBIAEABIADAAIABABIAAABIAABWIAAACIgBABIgCAAIgEAAIgDAAIgDAAIgBgBIAAgCIAAgMQgIAIgHAFQgHADgGAAQgJAAgGgCgAAKgvQgCgCAAgFQAAgFACgCQACgCAFAAQAGAAABACQACABAAAGQAAAFgCACQgCACgFAAQgFAAgCgCgAgXgvQgBgCAAgFQAAgFABgCQACgCAGAAQAFAAACACQACABAAAGQAAAFgCACQgCACgFAAQgGAAgCgCg");
	this.shape_35.setTransform(128,10.7);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgQAvIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAANIAHgJIAEgFIAGgDIAFAAIADAAIAEAAIADACIACABIAAABIABABIAAABIAAAEIAAAEIAAACIgBABIgBAAIgCAAIgDgBIgDgBIgEAAIgFABIgEADIgEAGIgGAJIAAA4IgBACIgBABIgCAAg");
	this.shape_36.setTransform(119.9,12.3);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgTA/QgHgCgFgDQgFgDgCgEQgCgFAAgFIABgGIACgGIAEgFIAGgFQgFgCgCgEQgDgEAAgEQAAgFADgEIAGgIIgFgIQgCgFAAgHQAAgHADgGQACgGAFgEQAEgEAHgDQAGgBAHAAIAGAAIAGABIAbAAQAAAAAAAAQABAAAAABQAAAAABAAQAAABAAAAIABAFIgBAEQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAIgNAAQAEAEABAEQABAEAAAEQAAAJgCAFQgDAGgEAEQgFAEgGADQgGACgGAAQgFgBgFgBQgFgCgCgCIgDAFIgBACQAAAEADACQADADAFAAIAVAAIAMADQAGABAEADQAEADACAFQACAEAAAFQAAAGgCAGQgDAGgFAEQgFAEgIACQgJACgJAAQgKAAgIgBgAgTAbIgDAFIgCADIAAAFQAAAGAGADQAHADALABQAFgBAFgBQAFgCADgCQADgCACgDQABgDAAgEQAAgFgFgDQgEgEgIABIgVgBgAgJgyQgEACgCADQgCADgBADIgBAHQAAAJAFAFQAEAFAJAAQADAAAEgCQADgBACgCQADgDABgEIABgHQAAgJgFgFQgFgFgHAAQgFAAgDABg");
	this.shape_37.setTransform(111.1,14.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgQAvIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAANIAHgJIAEgFIAGgDIAFAAIADAAIAEAAIADACIACABIAAABIABABIAAABIAAAEIAAAEIAAACIgBABIgBAAIgCAAIgDgBIgDgBIgEAAIgFABIgEADIgEAGIgGAJIAAA4IgBACIgBABIgCAAg");
	this.shape_38.setTransform(103.9,12.3);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgFgGgDgJQgDgJAAgMQAAgKADgJQADgJAFgGQAGgGAIgEQAIgDAIAAQAJAAAIADQAHAEAFAFQAFAGACAIQACAHAAAJIAAADQAAACgCABQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIg3AAIABANQABAGAEAEQADAEAGACQAFADAHAAIAKgBIAJgDIAGgCIADgBIACAAIAAABIABACIAAADIAAACIAAACIgBABIgBABIgCACIgIADIgJACIgMABQgJAAgIgDgAgIggQgFACgDAEIgEAJQgCAEAAAGIAtAAQABgNgGgHQgGgHgMAAQgEAAgEACg");
	this.shape_39.setTransform(94.8,12.4);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAMA7QgHAAgFgCQgCgCgEgDQgDgEgBgGIgBgNIAAgxIgNAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAAAAAgBIgBgFIAAgDIABgCIABgBIABgBIANAAIAAgVIAAgBIABgBIADAAIAEgBIADABIABAAIABABIABABIAAAVIAWAAIACABIABABIAAACIAAADIAAAFQgBABAAAAQAAAAAAAAQgBABAAAAQAAAAgBAAIgWAAIAAAvQAAAJACAFQADAEAHAAIAEAAIADgBIACgBIACgBIABABIABABIAAABIAAADIAAAFIgBACIgDACIgDABIgEABg");
	this.shape_40.setTransform(86.6,11.2);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AAdAvIgEAAIgCAAIgBgBIgBgCIAAgxIgBgMIgDgIIgGgGQgEgBgEAAQgEAAgGAEQgHAEgGAJIAAA7IgBACIgBABIgCAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhWIAAgBIABgBIACAAIAEgBIAEABIACAAIABABIAAABIAAAMQAIgJAHgDQAHgEAGAAQAJAAAGADQAGACADAGQAEAEACAIQABAGAAAKIAAAzIAAACIgBABIgDAAg");
	this.shape_41.setTransform(78.4,12.3);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AAABAIgCAAIgDAAIgBgBIgBgCIAAhWIABgBIABgBIADAAIACAAIAEAAIACAAIABABIAAABIAABWIAAACIgBABIgCAAgAgHguQgCgDAAgFQAAgGACgCQADgCAEAAQAFAAACACQACACAAAGQAAAGgCACQgCABgFAAQgFABgCgCg");
	this.shape_42.setTransform(70.9,10.6);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AAlA/IgFAAIgCAAIgCgBIAAgCIAAg4Ig3AAIAAA4IgBACIgBABIgDAAIgEAAIgEAAIgCAAIgCgBIAAgCIAAh3IAAgBIACgBIACgBIAEAAIAEAAIADABIABABIABABIAAAzIA3AAIAAgzIAAgBIACgBIACgBIAFAAIADAAIADABIACABIAAABIAAB3IAAACIgCABIgDAAg");
	this.shape_43.setTransform(62.4,10.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgMAYIgCAAIAAgBIAAgBIANgZIAAgNIAAgEIABgCIACgBIAEgBIAFABIACABIACACIAAAEIAAAGIgBAFIgBAEIgDADIgMAUIgBABIgBABIgCAAIgEABg");
	this.shape_44.setTransform(48.7,17.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AgKAvIgIgCIgGgCIgDgDIgCgCIAAgFIAAgDIAAgCIABgBIABgBIADACIAGADIAHACQAEACAGAAIAFgBIAFgDQADgBACgDIABgGQAAgEgCgDIgFgEIgIgEIgGgDIgIgDIgGgEIgGgHQgBgEAAgGQAAgFABgFQACgFAFgDQADgEAHgCQAGgCAFAAIAHABIAHABIAFACIADACIABABIABACIAAABIAAADIAAADIAAACIgBABIgBAAIgDgBIgEgCIgHgCIgIgBIgFABQgDAAgCACIgDAEIgBAFQAAAEACADIAFAEIAFAEIAIADIAJAEIAHADQADADACAEQABAEAAAFQAAAHgCAFQgDAGgEADQgEAEgHACQgGACgGAAg");
	this.shape_45.setTransform(42.8,12.4);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AAdAuIgGAAIgDAAIgBgCIgCgBIgRg+IAAAAIAAAAIgRA+IgBACIgCABIgCAAIgGAAIgEAAIgEAAIgCgCIgBgBIgZhRIgBgDIAAgCIAAgBIACgBIADAAIADAAIAEAAIADAAIACABIAAACIAVBGIAAABIAAgBIAUhGIABgCIABgBIADAAIACAAIAEAAIABAAIACABIAAABIAWBHIAAABIAAgBIAUhGIABgCIABgBIAEAAIADAAIAEAAIADAAIABABIAAABIAAACIgBADIgaBRIAAACIgCABIgEAAg");
	this.shape_46.setTransform(31.9,12.4);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgOAtQgIgDgGgGQgFgGgDgJQgDgJAAgMQAAgKADgJQADgJAFgGQAGgGAIgEQAIgDAIAAQAKAAAHADQAHAEAFAFQAEAGADAIQACAHAAAJIAAADQAAACgCABQgBABAAAAQgBAAAAAAQgBABAAAAQgBAAgBAAIg3AAIABANQACAGADAEQAEAEAFACQAGADAFAAIALgBIAJgDIAGgCIADgBIACAAIABABIAAACIAAADIAAACIAAACIAAABIgCABIgDACIgHADIgJACIgMABQgJAAgIgDgAgIggQgEACgDAEIgGAJQgBAEAAAGIAtAAQABgNgGgHQgGgHgLAAQgFAAgEACg");
	this.shape_47.setTransform(19.9,12.4);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAiA/IgEAAIgEgCIgEgFIgDgGIglhFIgGgNIgGgLIAAAAIAAAOIAAAOIAABLIAAACIgBABIgDAAIgEAAIgEAAIgDAAIgBgBIAAgCIAAhyQAAgFACgBQACgCADAAIAIAAIAFABIADABIADADIADAGIAcA1IAFAKIAFAJIAFAJIAEAJIABAAIgBgPIAAgQIAAhDIABgBIABgBIADgBIAEAAIAEAAIACABIACABIAAABIAAByIgBAEIgBACIgDACIgCAAg");
	this.shape_48.setTransform(8.5,10.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,490.6,24);


(lib.iPad = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.instance = new lib.freiesMagaziniPadAppSingle();
	this.instance.setTransform(0,340,1,1,-90);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,435,340);


(lib.Hintergrund = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Ebene 1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#666666","#000000"],[0,1],0,0,0,0,0,177.8).s().p("A67GuIAAtbMA13AAAIAANbg");
	this.shape.setTransform(364,45,2.11,1.047);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


// stage content:
(lib.freiesMagazinBanner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		canvas.onclick = function(event) {
		    window.open("http://www.freiesmagazin.de/", "_blank");
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(348));

	// Klickfläche (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("Eg43AHCIAAuDMBxvAAAIAAODg");
	mask.setTransform(364,45);

	// Slogan 4: iPad-App
	this.instance = new lib.Slogan4iPadApp();
	this.instance.setTransform(364,45,1,1,0,0,0,72.8,12);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(263).to({_off:false},0).to({alpha:1},24).wait(36).to({alpha:0},24).wait(1));

	// iPad
	this.instance_1 = new lib.iPad();
	this.instance_1.setTransform(96.1,43.1,0.641,0.641,0,0,0,217.6,170.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.instance_1.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(227).to({_off:false},0).wait(1).to({regX:217.5,regY:170,scaleX:0.63,scaleY:0.63,skewY:0.2,x:118.6,y:43,alpha:0.042},0).wait(1).to({scaleX:0.62,scaleY:0.62,skewY:0.5,x:141.1,alpha:0.083},0).wait(1).to({scaleX:0.61,scaleY:0.61,skewY:0.7,x:163.7,alpha:0.125},0).wait(1).to({scaleX:0.59,scaleY:0.59,skewY:1,x:186.3,alpha:0.167},0).wait(1).to({scaleX:0.58,scaleY:0.58,skewY:1.2,x:208.9,alpha:0.208},0).wait(1).to({scaleX:0.57,scaleY:0.57,skewY:1.5,x:231.5,y:43.1,alpha:0.25},0).wait(1).to({scaleX:0.56,scaleY:0.56,skewY:1.7,x:254.1,y:43,alpha:0.292},0).wait(1).to({scaleX:0.54,scaleY:0.54,skewY:1.9,x:276.6,alpha:0.333},0).wait(1).to({scaleX:0.53,scaleY:0.53,skewY:2.2,x:299.2,alpha:0.375},0).wait(1).to({scaleX:0.52,scaleY:0.52,skewY:2.4,x:321.8,alpha:0.417},0).wait(1).to({scaleX:0.51,scaleY:0.51,skewY:2.7,x:344.4,alpha:0.458},0).wait(1).to({scaleX:0.5,scaleY:0.5,skewY:2.9,x:367,alpha:0.5},0).wait(1).to({scaleX:0.48,scaleY:0.48,skewY:3.1,x:389.5,alpha:0.542},0).wait(1).to({scaleX:0.47,scaleY:0.47,skewY:3.4,x:412.1,alpha:0.583},0).wait(1).to({scaleX:0.46,scaleY:0.46,skewY:3.6,x:434.7,alpha:0.625},0).wait(1).to({scaleX:0.45,scaleY:0.45,skewY:3.9,x:457.3,alpha:0.667},0).wait(1).to({scaleX:0.44,scaleY:0.44,skewY:4.1,x:479.9,alpha:0.708},0).wait(1).to({scaleX:0.42,scaleY:0.42,skewY:4.4,x:502.5,alpha:0.75},0).wait(1).to({scaleX:0.41,scaleY:0.41,skewY:4.6,x:525,y:43.1,alpha:0.792},0).wait(1).to({scaleX:0.4,scaleY:0.4,skewY:4.8,x:547.6,y:43,alpha:0.833},0).wait(1).to({scaleX:0.39,scaleY:0.39,skewY:5.1,x:570.2,y:43.1,alpha:0.875},0).wait(1).to({scaleX:0.37,scaleY:0.37,skewY:5.3,x:592.8,alpha:0.917},0).wait(1).to({scaleX:0.36,scaleY:0.36,skewY:5.6,x:615.3,y:43,alpha:0.958},0).wait(1).to({scaleX:0.35,scaleY:0.35,skewY:5.8,x:637.9,alpha:1},0).wait(1).to({y:43.1},0).wait(1).to({scaleX:0.35,scaleY:0.35,y:43},0).wait(2).to({scaleY:0.35,x:638},0).wait(1).to({scaleX:0.35,y:43.1},0).wait(1).to({x:637.9,y:43},0).wait(1).to({scaleX:0.35,scaleY:0.35,y:43.1},0).wait(1).to({y:43},0).wait(1).to({scaleX:0.35,scaleY:0.35},0).wait(2).to({scaleY:0.36},0).wait(1).to({scaleX:0.36,x:638,y:43.1},0).wait(1).to({y:43},0).wait(1).to({scaleX:0.36,scaleY:0.36,x:637.9},0).wait(2).to({scaleX:0.36,scaleY:0.36},0).wait(2).to({scaleY:0.36,y:43.1},0).wait(1).to({scaleX:0.36,x:638,y:43},0).wait(2).to({scaleX:0.36,scaleY:0.36,x:637.9},0).wait(2).to({scaleX:0.36,scaleY:0.36},0).wait(1).to({y:43.1},0).wait(1).to({scaleY:0.36,y:43},0).wait(1).to({scaleX:0.36},0).wait(1).to({scaleY:0.36,x:638},0).wait(1).to({scaleX:0.36,y:43.1},0).wait(1).to({x:637.9,y:43},0).wait(1).to({scaleX:0.36,scaleY:0.36,y:43.1},0).wait(1).to({y:43},0).wait(1).to({scaleY:0.36,y:43.1},0).wait(1).to({scaleX:0.36,y:43},0).wait(1).to({scaleY:0.37},0).wait(1).to({scaleX:0.37,x:638,y:43.1},0).wait(1).to({x:637.9,y:43},0).wait(1).to({scaleX:0.37,scaleY:0.37},0).wait(2).to({scaleY:0.37},0).wait(1).to({scaleX:0.37},0).wait(1).to({scaleY:0.37,y:43.1},0).wait(1).to({scaleX:0.37,x:638,y:43},0).wait(2).to({scaleX:0.37,scaleY:0.37,x:637.9},0).wait(2).to({scaleX:0.37,scaleY:0.37},0).wait(1).to({y:43.1},0).wait(1).to({scaleY:0.37,y:43},0).wait(1).to({scaleX:0.37},0).wait(1).to({scaleY:0.37,x:638},0).wait(1).to({scaleX:0.37},0).wait(1).to({x:637.9,y:43.1},0).wait(1).to({scaleX:0.37,scaleY:0.37},0).wait(1).to({y:43},0).wait(1).to({scaleY:0.37},0).wait(1).to({scaleX:0.37},0).wait(1).to({scaleY:0.38,x:638},0).wait(1).to({scaleX:0.38,y:43.1},0).wait(1).to({x:637.9,y:43},0).wait(1).to({scaleX:0.38,scaleY:0.38},0).wait(2).to({scaleY:0.38},0).wait(1).to({scaleX:0.38},0).wait(1).to({scaleY:0.38,y:43.1},0).wait(1).to({scaleX:0.38,x:638,y:43},0).wait(2).to({scaleX:0.38,scaleY:0.38,x:637.9},0).wait(2).to({scaleY:0.38},0).wait(1).to({scaleX:0.38,y:43.1},0).wait(1).to({scaleY:0.38,y:43},0).wait(1).to({scaleX:0.38,y:43.1},0).wait(1).to({alpha:0.958},0).wait(1).to({alpha:0.917},0).wait(1).to({alpha:0.875},0).wait(1).to({alpha:0.833},0).wait(1).to({alpha:0.792},0).wait(1).to({alpha:0.75},0).wait(1).to({alpha:0.708},0).wait(1).to({alpha:0.667},0).wait(1).to({alpha:0.625},0).wait(1).to({alpha:0.583},0).wait(1).to({alpha:0.542},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.458},0).wait(1).to({alpha:0.417},0).wait(1).to({alpha:0.375},0).wait(1).to({alpha:0.333},0).wait(1).to({alpha:0.292},0).wait(1).to({alpha:0.25},0).wait(1).to({alpha:0.208},0).wait(1).to({alpha:0.167},0).wait(1).to({alpha:0.125},0).wait(1).to({alpha:0.083},0).wait(1).to({alpha:0.042},0).wait(1).to({alpha:0},0).wait(1));

	// Slogan 3: freiesMagazin
	this.instance_2 = new lib.Slogan3freiesMagazin();
	this.instance_2.setTransform(364.1,45,1,1,0,0,0,100.8,19);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.instance_2.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(167).to({_off:false},0).to({alpha:1},24).wait(36).to({alpha:0},24).to({_off:true},1).wait(96));

	// Slogan 2: Kostenlos
	this.instance_3 = new lib.Slogan2Kostenlos();
	this.instance_3.setTransform(364.1,45,1,1,0,0,0,131.1,12);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.instance_3.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(83).to({_off:false},0).to({alpha:1},24).wait(36).to({alpha:0},24).to({_off:true},1).wait(180));

	// Slogan 1: News
	this.instance_4 = new lib.Slogan1News();
	this.instance_4.setTransform(364,45,1,1,0,0,0,245.3,12);
	this.instance_4.alpha = 0;

	this.instance_4.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({alpha:1},23).wait(36).to({alpha:0},24).to({_off:true},1).wait(264));

	// Hintergrund
	this.instance_5 = new lib.Hintergrund();
	this.instance_5.setTransform(364,45,1,1,0,0,0,364,45);

	this.instance_5.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(348));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(364,45,728,90);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;